### ISSUE TITLE
Consideration for wildcard entries

### ISSUE THREAD

**Issue by v1k0d3n** [Orange-OpenSource/PowerDNS-Operator#67]
Nice work on this operator! I've been exploring this project over the weekend, and I really like it a lot. Thank you for sharing it. I was even surprised that LUA records seem to take (although admittedly I need to test this a bit more still).

Example:
```
oc get rrsets.dns.cav.enablers.ob -n jinkit-ops \
  | awk 'NR == 1 || /telco-ocp-run/'

NAME                                                                 ZONE             NAME                                                                             TYPE   TTL    STATUS      RECORDS
api-sm-us-ztp-telco-ocp-run-lua                                      telco-ocp-run    api.sm.us.ztp.telco.ocp.run.telco-ocp-run.                                       LUA     1      Succeeded   ["A \"ifportup(6443, {'192.168.3.91', '192.168.3.92', '192.168.3.93', '192.168.3.94'}, {selector='hashed'})\""]
```

One thing I think I'm missing...is how to implement wildcard A records? PDNS administrators can do this today. It would be really nice to retain this functionality for things like OpenShift deployments. But it doesn't seem like the `RRSet` object can handle this entry currently. Is this assumption correct?

**Comment by mydoomfr** [comment]
Hello @v1k0d3n ,

Unfortunately, the documentation is not yet finished and lacks examples.

However, here is an example of a wildcard A record 🎅 

 https://github.com/Orange-OpenSource/PowerDNS-Operator/blob/b6ffdc27c634ca9b6aba99fdb9e04a58d1e877be/config/samples/dns_v1alpha1_rrset.yaml#L86-L99

**Comment by v1k0d3n** [comment]
That's so wild...I was literally just testing this now, and when I came back to close out the issue you had already responded. Thank you so much for the quick response! Have a wonderful holiday break... 🎅

Thanks again to everyone for contributing to the project!
